# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08ac8d26e73c8dac44f40a9b927be5c84210ff3e4d990372693e8a50d8f8d633df024bec447d2877dfe8894652fb4e2a7a218fd32236de13c0b22aa4b44b0e4f

test:
  secret_key_base: 346f60e6983d9528533f446824faa785f51febcf1b35545333381b7924159213f4135a50ca475925466f926a5a7dab7ec88400d61ccfcb21b471e2e457302550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
